#!/usr/bin/env python3
"""Build backend/data/training_data.json from curated seeds + realistic variants.

Run from project root:
    python backend/scripts/build_training_data.py
"""
from __future__ import annotations

import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
BACKEND = ROOT / "backend"
sys.path.insert(0, str(BACKEND))

from ml_nlp import TRAINING_DATA_FALLBACK  # noqa: E402

OUT = BACKEND / "data" / "training_data.json"

# Extra curated samples beyond TRAINING_DATA_FALLBACK — Indian merchants & phrasing.
EXTRA_SAMPLES: dict[str, list[str]] = {
    "Income": [
        "hdfc salary credit", "icici salary neft", "axis payroll", "wipro salary",
        "tcs salary credit", "infosys salary", "cognizant payroll", "accenture salary",
        "hcl salary credit", "capgemini salary", "amazon seller payout", "meesho seller payment",
        "instamojo payout", "razorpay settlement", "stripe payout india", "youtube ad revenue",
        "google adsense payment", "affiliate commission", "referral bonus credited",
        "annual bonus credit", "joining bonus", "retention bonus", "incentive credited",
        "overtime pay", "shift allowance", "hra reimbursement", "medical reimbursement",
        "leave encashment", "gratuity payment", "pf withdrawal", "epf withdrawal",
        "nps withdrawal", "mutual fund redemption credit", "stock sale proceeds",
        "dividend from hdfc bank", "interest on savings", "fd maturity credit",
        "rd maturity amount", "ppf withdrawal", "insurance maturity claim",
        "rental income received", "airbnb payout", "olx sale payment received",
        "cash deposit by customer", "payment received via gpay", "phonepe payment received",
        "collect request from rahul", "money received from wife", "transfer from savings",
        "cashback earned amazon", "amazon pay cashback", "credit card cashback",
        "bank interest credit", "savings account interest", "fd interest credited",
        "stock dividend credited", "mutual fund dividend", "tax refund received",
        "gst refund received", "upi collect request payment", "rent received from tenant",
        "olx sale proceeds", "flipkart sale payment", "gift received birthday",
        "diwali bonus received", "performance bonus payout", "commission earned affiliate",
        "blog income google adsense", "content writing payment", "referral bonus cred", "salry credit", "sallery received", "cashbak amazon", "bonas credited",
    ],
    "Food Delivery": [
        "swiggy instamart groceries", "swiggy one membership order", "zomato pro order",
        "zomato hyperpure", "eatclub order", "tossin pizza delivery", "la pinoz pizza",
        "oven story pizza", "nomad pizza delivery", "onesta pizza", "california burrito",
        "taco bell delivery", "subway delivery", "burger king delivery", "wendy's delivery",
        "starbucks delivery swiggy", "third wave delivery", "chaayos delivery",
        "momo zone delivery", "wow momo delivery", "haldiram delivery swiggy",
        "paradise biryani delivery", "biryani by kilo", "lunch box delivery",
        "tiffin service monthly", "homemade food delivery", "cloud kitchen order", "swigy order", "swiggyy dinner", "zomatoo order", "zomatto lunch", "food panda order",
    ],
    "Food & Dining": [
        "barbeque nation buffet", "mainland china restaurant", "punjabi by nature",
        "punjabi tadka", "punjabi tadka restaurant", "takatak", "takatak food",
        "taka tak", "aloo paratha", "aloo parantha", "aloo paratntha", "paneer paratha",
        "gobi paratha", "methi paratha", "mix paratha", "butter naan", "garlic naan",
        "chole bhature", "chole bhatura", "dal makhani", "dal tadka", "paneer tikka",
        "paneer butter masala", "butter chicken", "chicken tikka", "mutton rogan josh",
        "fish fry", "veg thali", "non veg thali", "punjabi thali", "rajasthani thali",
        "south indian meals", "north indian lunch", "dosa plate", "masala dosa",
        "rava dosa", "mysore masala dosa", "idli vada", "medu vada", "uttapam",
        "pav bhaji", "misal pav", "vada pav",
        "seekh kebab", "tandoori chicken", "roomali roti",
        "bikanervala", "bikanerwala", "haldiram dine", "sagar ratna lunch",
        "saravana bhavan breakfast", "mtr rava idli", "rajdhani thali restaurant",
        "soup and salad", "dhaba dinner",
        "highway dhaba", "local restaurant bill", "tiffin center lunch",
        "canteen food coupon", "office cafeteria", "food court lunch",
        "social offline dining", "truffles cafe bill", "third wave cafe bill",
        "chaayos outlet", "nandini hotel lunch", "taj hotel dinner",
        "social kitchen bar", "hard rock cafe",
        "beer cafe bill", "brewery bill", "sushi bar dinner", "thai restaurant",
        "korean restaurant bill", "italian restaurant", "mexican grill",
        "office team lunch", "client dinner meeting", "birthday dinner restaurant",
        "anniversary dinner", "family lunch outing", "weekend brunch",
        "goli vada pav", "panchavati restaurant", "naivedyam meals",
        "andhra meals", "kerala parotta", "appam stew", "puttu kadala",
        "pongal breakfast", "pesarattu chutney", "hyderabadi biryani dine",
        "lucknowi biryani", "kebab corner",
        "ccd coffee", "chaayos chai", "tea post chai", "biryani blue restaurant",
        "paradise biryani", "behrouz biryani", "dhaba near highway lunch",
        "joshi mess mess bill", "annapurna mess monthly mess",
    ],
    "Fast Food": [
        "pizza margherita", "pepperoni pizza", "dominos pizza order",
        "pizza hut pan pizza", "la pinoz pizza", "burger king whopper",
        "mcdonald's happy meal", "kfc fried chicken bucket", "subway footlong",
        "taco bell crunchwrap", "burger and fries", "french fries",
        "momos steamed plate", "chicken momos", "wow momo", "kathi roll",
        "egg roll", "chicken roll", "frankie roll", "shawarma roll",
        "chicken shawarma", "veg sandwich", "grilled sandwich",
        "chowmein", "hakka noodles", "fried rice lunch", "manchurian dry",
        "noodles manchurian", "sizzler plate", "nandos chicken meal",
        "taco bell meal", "subway sandwich footlong", "roll king",
        "frankie junction", "chinese sizzler", "pizza express dine in",
    ],
    "Groceries": [
        "blinkit 10 min delivery", "zepto groceries", "bigbasket monthly order",
        "jiomart essentials", "dmart monthly stock", "reliance smart groceries",
        "more supermarket bill", "spencers daily needs", "nature's basket organic",
        "ratnadeep super market", "lulu hypermarket", "star bazaar groceries",
        "local kirana monthly", "vegetable vendor",
        "onions potatoes tomatoes", "atta rice dal oil", "monthly ration stock",
        "amul butter milk eggs", "mother dairy products", "organic vegetables box",
        "farm fresh basket", "milkbasket subscription", "country delight milk", "bigbaskt order", "blinkit grocerys", "zepto groceris", "vegitable market",
    ],
    "Fuel": [
        "hp petrol pump sector 18", "iocl diesel fill", "bpcl petrol noida",
        "shell fuel station", "nayara energy petrol", "reliance petrol pump",
        "bike petrol fill", "car diesel tank full", "cng fill station",
        "auto lpg refill", "highway toll petrol", "interstate fuel stop",
        "ev charging station", "tata power ev charging", "scooty petrol",
        "jio bp petrol", "cng refill pump", "petorl pump", "petrol pum", "diesal fill", "gasoline pump",
    ],
    "Transportation": [
        "ola outstation trip", "uber intercity", "rapido bike ride", "rapido auto fare",
        "delhi metro smart card", "mumbai local train ticket", "irctc tatkal booking",
        "irctc ac 2 tier", "redbus sleeper bus", "abhibus volvo", "makemytrip flight",
        "goibibo flight booking", "indigo flight delhi mumbai", "vistara economy",
        "spicejet ticket", "air india domestic", "fastag recharge paytm",
        "highway toll plaza", "parking mall select city", "valet parking charge",
        "zoomcar rental", "revv self drive", "bounce scooter ride", "yulu bike rent",
        "meru cab airport", "mega cab", "savaari outstation", "blusmart ev cab", "uberr ride", "olaa cab", "rapidoo bike", "mettro ticket",
    ],
    "Shopping": [
        "amazon great indian sale", "amazon pay shopping", "flipkart big billion days",
        "myntra end of reason sale", "ajio fashion order", "meesho reseller order",
        "nykaa beauty order", "croma electronics", "reliance digital tv",
        "vijay sales ac", "boat airdopes", "noise smartwatch", "fire boltt watch",
        "oneplus buds", "samsung galaxy phone", "iphone purchase emi",
        "macbook air purchase", "dell laptop order", "hp printer ink",
        "ikea furniture", "pepperfry sofa", "urban ladder bed", "home centre decor",
        "decathlon sports shoes", "puma running shoes", "nike air max",
        "h&m shirt", "zara dress", "westside kurta", "pantaloons formal wear",
        "shoppers stop sale", "lifestyle store", "central mall shopping",
        "amazon basics order", "flipkart grocery appliances", "tatacliq fashion",
    ],
    "Utilities": [
        "bescom electricity bill", "tata power online payment", "msedcl maharashtra bill",
        "bwssb water bill bangalore", "delhi jal board", "indraprastha gas bill",
        "igl piped gas payment", "airtel postpaid bill", "jio postpaid recharge",
        "vi mobile bill", "bsnl landline bill", "jio fiber monthly bill",
        "act fibernet bill", "hathway broadband", "tata play dth recharge",
        "dish tv recharge", "sun direct dth", "airtel dth pack",
        "property tax online", "mcd property tax", "bbmp property tax",
        "traffic challan payment", "driving licence fee", "vehicle rc renewal",
        "pollution certificate fee", "lpg cylinder booking indane",
        "bses electricity bill", "adani electricity bill", "torrent power bill",
        "jio fiber broadband", "airtel broadband bill", "act fibernet recharge",
        "broadband wifi recharge", "corporation water tax", "elecricity bill", "elektricity bill", "airtel bil", "rechrge phone",
    ],
    "Subscriptions": [
        "netflix monthly plan", "spotify premium india", "amazon prime annual",
        "disney hotstar super", "sony liv premium", "zee5 premium", "jio cinema plus",
        "youtube premium family", "apple music subscription", "google one 100gb",
        "microsoft 365 personal", "adobe creative cloud", "canva pro annual",
        "notion plus plan", "github pro subscription", "chatgpt plus renewal",
        "cult fit elite membership", "cure fit live", "gold gym monthly",
        "anytime fitness annual", "kindle unlimited", "audible membership",
        "icloud plus storage", "medium membership", "headspace meditation subscription",
        "swiggy one membership", "zomato gold membership", "hotstar subscription",
        "sony liv annual", "wynk music premium", "gaana plus subscription",
    ],
    "Entertainment": [
        "bookmyshow pvr ticket", "inox movie couple seat", "carnival cinemas",
        "cinepolis recliner", "netflix watch party snacks", "steam game purchase",
        "playstation store game", "xbox game pass ultimate", "epic games fortnite vbucks",
        "bgmi uc purchase", "wonderla tickets", "imagica theme park",
        "kingdom of dreams show", "comedy show ticket", "standup comedy live",
        "concert ticket bookmyshow", "ipl match ticket", "cricket stadium ticket",
        "pubg uc purchase", "freefire diamonds", "valorant points purchase",
        "temple donation online", "amusement park entry", "water park ticket",
        "museum entry fee", "hockey match ticket", "concert festival pass",
    ],
    "Health": [
        "apollo pharmacy medicines", "medplus monthly medicines", "pharmeasy order",
        "tata 1mg delivery", "netmeds prescription", "truemeds generic medicines",
        "practo doctor consultation", "mfine online consult", "thyrocare full body test",
        "dr lal path labs", "metropolis blood test", "apollo diagnostics package",
        "dental checkup clinic", "eye test lenskart", "specsmakers glasses",
        "physiotherapy session", "yoga class wellness", "gym protein supplement",
        "hospital opd fee", "emergency room bill", "health insurance copay",
    ],
    "Education": [
        "udemy course purchase", "coursera specialization", "unacademy plus subscription",
        "byjus class fees", "vedantu live classes", "whitehat jr coding",
        "school annual fees", "college semester fees", "university tuition",
        "coaching iit jee", "neet coaching fees", "gate test series",
        "amazon books order", "flipkart textbooks", "stationery shop school",
        "exam form fee", "certification exam aws", "google cloud certification",
    ],
    "Investments": [
        "zerodha sip mutual fund", "groww sip installment", "upstox equity buy",
        "paytm money sip", "kuvera direct plan", "coin by zerodha mf",
        "hdfc securities trade", "icici direct stocks", "angel one brokerage",
        "ppf deposit post office", "nps contribution tier 1", "elss tax saving sip",
        "fixed deposit hdfc", "recurring deposit sbi", "sovereign gold bond",
        "wazirx crypto buy", "coindcx bitcoin", "term plan hdfc life premium",
        "health insurance policy premium", "lic premium payment",
        "gold etf purchase", "silver etf buy", "epf contribution",
        "fd account deposit", "rd account monthly", "sgb investment",
        "cryptocurrency bitcoin buy", "ethereum eth purchase", "trading account funded", "zerodah sip", "groww investmnt", "upstx equity buy", "mutul fund sip", "tradng account", "intrady order", "zerodha intraday order", "zerodha delivery trade", "zerodha brokerage charge", "groww stock order", "groww options trading", "upstox intraday buy", "upstox futures order", "angel one sell order", "angel one option buy", "5paisa ipo application", "hdfc securities brokerage fee", "icici direct buy order", "kotak securities intraday", "sharekhan stock trade", "motilal oswal futures", "nse stock purchase", "bse equity order", "stock market brokerage", "demat annual maintenance charge", "trading account margin", "margin pledge fee", "call option premium paid", "put option premium", "futures contract buy", "ipo application upi", "ipo allotment payment", "buy shares online", "sell shares proceeds", "equity delivery order", "day trading charge",
    ],
    "Housing/Rent": [
        "house rent january", "flat rent upi", "pg rent monthly", "hostel fees semester",
        "society maintenance june", "apartment maintenance charge", "builder floor rent",
        "security deposit landlord", "brokerage flat rent", "stamp duty registration",
        "home loan emi hdfc", "housing loan sbi emi", "property tax society",
    ],
    "Personal Care": [
        "lakme salon haircut", "looks salon facial", "urban company grooming",
        "nykaa cosmetics order", "mamaearth skincare", "plum body lotion",
        "dove shampoo purchase", "gillette razor blades", "colgate toothpaste",
        "himalaya face wash", "nivea moisturizer", "ponds cream",
        "mehndi bridal package", "spa body massage", "nail art parlour",
        "jawed habib salon", "naturals salon", "green trends salon",
        "facial treatment salon", "manicure pedicure", "beauty parlour visit",
        "waxing salon", "perfume deodorant", "skincare products buy",
        "sunscreen lotion purchase", "face wash cream", "shampoo conditioner buy",
        "cosmetics makeup items", "hair oil purchase", "shaving razor", "facewsh purchase", "facewashh", "shampu purchase", "moisturiser cream", "cosmetcs order",
    ],
    "Snacks": [
        "lay's chips packet", "kurkure masala munch", "haldiram namkeen",
        "bikaji bhujia", "parle g biscuits", "oreo cookies pack",
        "dairy milk silk", "kitkat break", "snickers bar", "munch chocolate",
        "maggi 2 minute", "yippee noodles", "chai tapri", "cutting chai",
        "ice cream corner", "kwality walls", "amul ice cream",
        "samosa street vendor", "vada pav stall", "pani puri evening", "kurkuree packet", "layss chips", "samosaa",
    ],
    "Fruits": [
        "mango purchase", "ripe mangoes", "mango box", "banana bunch",
        "bananas 6 piece", "apples from vendor", "grapes kilo",
        "watermelon slice", "muskmelon fruit", "papaya fruit", "guava fruit",
        "pineapple fruit", "pomegranate", "strawberry box", "kiwi fruit",
        "seasonal fruits", "fruit salad bowl", "fruit market purchase",
        "fruit stall vendor", "oranges half kilo", "mosambi juice fruit",
    ],
    "Refreshments": [
        "fresh juice stall", "orange juice glass", "mango juice pack",
        "lemonade stand", "nimbu pani", "mineral water bottle",
        "bottled water", "packaged drinking water", "coke cold drink",
        "pepsi can", "sprite bottle", "thums up", "limca", "maaza mango drink",
        "frooti tetra pack", "cold drink", "soft drink bottle", "soda water",
        "real juice pack", "lime water", "lime soda", "minute maid orange",
        "fresh lime soda",
    ],
    "Beverages": [
        "chocolate shake", "milkshake parlour", "banana shake",
        "cold coffee shake", "iced coffee", "iced tea", "lassi sweet shop",
        "chaas glass", "buttermilk", "smoothie bowl", "protein shake",
        "energy drink red bull", "horlicks", "bournvita malt",
        "starbucks frappuccino", "costa coffee latte", "dunkin donuts coffee",
        " CCD cold coffee", "cafe coffee day mocha", "third wave coffee",
        "barista espresso", "blue tokai coffee", "starbucks cappuccino",
        "tea time chai", "masala chai", "ginger tea", "green tea",
        "herbal tea", "kullad chai", "adrak chai", "elaichi chai",
        "filter coffee madras", "south indian filter coffee", "kaapi",
        "badam milk", "thandai drink", "rose milk", "kesar milk",
        "badam shake", "mango shake", "strawberry shake", "chikoo shake",
        "papaya shake", "sitaphal shake", "anar juice", "jamun juice",
        "sugarcane juice", "ganne ka ras", "coconut water tender",
        "nariyal pani", "lassi salted", "sweet lassi", "mango lassi",
        "rose lassi", "kesar lassi", "buttermilk masala", "chaas spicy",
        "aam panna", "jaljeera", "panakam", "bel sherbet",
        "sattu drink", "bael juice", "kokum sherbet", "sol kadhi",
    ],
    "Electronics": [
        "samsung smartphone purchase", "oneplus mobile buy", "redmi phone order",
        "realme mobile", "vivo smartphone", "oppo phone", "iphone 15 pro max",
        "iphone 14 purchase", "macbook pro m3", "macbook air m2", "ipad pro",
        "airpods pro 2", "airpods max", "apple watch ultra", "samsung galaxy watch",
        "garmin watch", "fitbit charge", "oneplus watch", "boat smart watch",
        "noise colorfit pro", "fire boltt call", "realme watch", "mi band",
        "sony wh-1000xm5", "bose quietcomfort", "jbl headphones", "boat earbuds",
        "realme buds", "oneplus buds", "samsung buds", "apple earpods",
        "sony camera alpha", "canon eos r5", "nikon z6", "fujifilm xt5",
        "gopro hero 12", "dji mini 4 pro", "insta360 camera", "dslr lens",
        "prime lens purchase", "zoom lens", "tripod stand", "camera gimbal",
        "lg oled tv", "samsung neo qled", "sony bravia", "tcl 4k tv",
        "mi smart tv", "oneplus tv", "hisense tv", "vizio tv",
        "playstation 5", "xbox series x", "nintendo switch oled", "steam deck",
        "gaming laptop", "asus rog", "msi katana", "alienware laptop",
        "razer blade", "lenovo legion", "hp omen", "dell g series",
        "gaming monitor", "lg ultragear", "samsung odyssey", "asus tuf",
        "mechanical keyboard", "gaming mouse", "logitech g pro", "razer deathadder",
        "steelseries mouse", "corsair keyboard", "keychron keyboard", "epomaker",
        "external hard drive", "ssd 1tb", "samsung t7", "sandisk extreme",
        "wd elements", "seagate backup", "nas storage", "cloud storage",
        "router wifi 6", "tp-link archer", "asus router", "netgear orbi",
        "mesh wifi system", "eero pro", "google nest wifi", "amplifi hd",
        "smart home hub", "google home", "amazon echo", "apple homepod",
        "philips hue lights", "smart bulbs", "smart switches", "smart plugs",
    ],
    "Gifts": [
        "birthday gift for friend", "anniversary gift wife", "wedding gift couple",
        "diwali gifts family", "christmas presents", "new year gift",
        "raksha bandhan gift", "bhai dooj gift", "karwa chauth gift",
        "valentine day gift", "friendship day gift", "teacher day gift",
        "gift card amazon", "flipkart gift voucher", "paytm gift card",
        "starbucks gift card", "ikea gift card", "apple gift card",
        "spotify gift card", "netflix gift subscription", "prime gift membership",
        "flower bouquet delivery", "cake midnight delivery", "chocolates gift pack",
        "perfume gift set", "watch gift", "jewelry gift gold", "silver gift items",
        "customized gift", "personalized gift", "photo frame gift", "custom mug",
        "gift hamper", "corporate gift", "client gift", "employee appreciation gift",
        "housewarming gift", "baby shower gift", "engagement gift",
    ],
    "Charity": [
        "donation pm cares", "red cross donation", "unicef contribution",
        "ngo donation india", "charity trust donation", "religious donation temple",
        "mosque donation", "church offering", "gurudwara langar seva",
        "crowdfunding contribution", "ketto donation", "milaap fund",
        "go fund me contribution", "medical fundraiser", "education fund donation",
        "orphanage donation", "old age home contribution", "animal shelter donation",
        "environmental charity", "tree plantation donation", "water conservation fund",
        "disaster relief fund", "flood relief donation", "earthquake relief",
        "covid relief fund", "oxygen concentrator donation", "hospital equipment donation",
        "blood donation camp", "organ donation pledge", "body donation",
        "scholarship fund donation", "education sponsor child", "adopt child education",
        "food donation drive", "clothes donation old", "book donation library",
        "religious pilgrimage donation", "temple renovation fund", "mosque construction",
    ],
    "Travel": [
        "flight booking delhi mumbai", "air india ticket", "indigo airlines",
        "vistara premium economy", "spicejet booking", "go air flight",
        "akasa air ticket", "international flight usa", "dubai flight booking",
        "singapore airlines", "emirates flight", "qatar airways", "etihad airways",
        "hotel booking oyo", "treebo hotel stay", "fabhotel reservation",
        "marriott hotel booking", "taj hotel stay", "oberoi hotel",
        "itc grand hotel", "hyatt regency", "hilton hotel", "radisson blu",
        "airbnb apartment stay", "homestay booking", "villa rental goa",
        "resort booking mahabaleshwar", "hill station stay", "beach resort",
        "visa application fee", "passport renewal fee", "travel insurance",
        "foreign exchange forex", "currency conversion", "travel card load",
        "tour package booking", "travel agency package", "group tour",
        "honeymoon package", "family vacation package", "adventure tour",
        "pilgrimage tour", "religious tour package", "temple tour",
        "cruise booking", "ship cruise", "luxury cruise",
        "train ticket irctc", "rajdhani express", "shatabdi express",
        "duronto express", "vande bharat", "tejas express",
        "tatkal booking", "premium tatkal", "current reservation",
        "sleeper class ticket", "ac 3 tier", "ac 2 tier", "first class ac",
        "bus ticket redbus", "volvo multi axle", "sleeper bus",
        "private bus ticket", "state transport bus", "luxury coach",
        "cab rental outstation", "self drive car", "chauffeur driven car",
        "airport transfer", "local sightseeing cab", "tourist vehicle",
    ],
    "Office Expenses": [
        "office supplies purchase", "stationery order", "printer paper ream",
        "ink cartridge replacement", "toner cartridge", "office furniture",
        "ergonomic chair", "standing desk", "office desk", "filing cabinet",
        "whiteboard purchase", "projector office", "conference room equipment",
        "video conferencing tool", "zoom subscription business", "microsoft teams",
        "slack business plan", "google workspace", "office 365 business",
        "software license purchase", "adobe license team", "canva pro team",
        "cloud storage business", "aws bill", "azure subscription", "gcp billing",
        "domain renewal", "web hosting annual", "ssl certificate",
        "website maintenance", "seo services", "digital marketing agency",
        "business cards printing", "brochure printing", "marketing material",
        "event sponsorship", "trade show booth", "conference registration",
        "client meeting dinner", "business travel flight", "hotel stay business",
        "team outing lunch", "office party expense", "employee engagement",
        "training program fee", "certification course", "workshop attendance",
        "consulting fee", "legal services", "accounting services",
        "audit fees", "tax consultant", "compliance cost",
    ],
    "Home Maintenance": [
        "plumber service charge", "electrician visit fee", "carpenter work",
        "painter labor charge", "ac repair service", "refrigerator repair",
        "washing machine service", "dishwasher repair", "microwave repair",
        "water purifier service", "ro filter change", "water tank cleaning",
        "pest control service", "termite treatment", "fumigation service",
        "deep cleaning service", "house cleaning monthly", "sofa cleaning",
        "carpet cleaning", "upholstery cleaning", "curtain dry cleaning",
        "gardener monthly", "lawn mowing service", "garden maintenance",
        "plant nursery purchase", "fertilizer bags", "gardening tools",
        "home renovation material", "cement bags", "sand purchase",
        "bricks order", "paint buckets", "hardware store purchase",
        "door lock replacement", "window repair", "glass replacement",
        "plumbing fixtures", "electrical switches", "light fixtures",
        "ceiling fan purchase", "exhaust fan", "geyser installation",
        "water heater repair", "solar panel installation", "inverter battery",
        "generator fuel", "generator service", "ups battery replacement",
        "security camera installation", "cctv system", "smart lock",
        "intercom system", "doorbell camera", "alarm system",
        "roof repair work", "waterproofing terrace", "wall crack repair",
        "termite proofing", "dampness treatment", "wall damp solution",
        "chimney cleaning kitchen", "exhaust fan cleaning", "drain cleaning",
        "sewer line cleaning", "gutter cleaning", "rainwater harvesting",
        "water tank installation", "sump pump service", "borewell maintenance",
        "elevator maintenance", "lift service charge", "staircase repair",
        "balcony repair", "railing replacement", "grill installation",
        "window grill fitting", "security door installation", "main door lock",
        "gate automation", "automatic gate opener", "garage door repair",
        "fencing installation", "compound wall repair", "boundary wall painting",
        "interior painting", "exterior painting", "texture painting",
        "wallpaper installation", "false ceiling work", "pop design ceiling",
        "modular kitchen installation", "kitchen cabinet repair", "countertop replacement",
        "sink replacement", "faucet repair", "tap replacement",
        "shower installation", "bathroom fittings", "sanitary ware",
        "toilet repair", "commode replacement", "wash basin installation",
        "mirror installation", "bathroom accessories", "towel rack",
        "curtain rod installation", "blind installation", "window blinds",
        "curtain purchase", "bedsheet purchase", "pillow covers",
        "mattress purchase", "sofa set buying", "dining table purchase",
        "wardrobe installation", "almirah purchase", "shelf installation",
        "rack installation", "storage cabinet", "shoe rack",
        "coat stand", "wall shelf", "floating shelves",
    ],
    "Automotive": [
        "car service maruti", "bike service honda", "scooty service activa",
        "car oil change", "engine oil top up", "brake fluid replacement",
        "coolant refill", "power steering fluid", "transmission oil",
        "car battery replacement", "bike battery new", "battery charge",
        "car tyre change", "bike tube replacement", "tyre rotation",
        "wheel alignment", "wheel balancing", "nitrogen air fill",
        "car wash premium", "bike wash service", "pressure wash",
        "car detailing", "ceramic coating", "teflon coating",
        "car polish", "wax polish", "interior cleaning",
        "seat cover purchase", "car mats", "floor mats",
        "steering cover", "gear knob", "car perfume",
        "car accessories", "bike accessories", "helmet purchase",
        "riding jacket", "riding gloves", "knee guards",
        "car insurance renewal", "bike insurance policy", "third party insurance",
        "comprehensive insurance", "zero dep insurance", "insurance claim",
        "car repair denting", "painting scratch", "bumper replacement",
        "headlight replacement", "tail light fix", "indicator repair",
        "wiper blade change", "horn repair", "mirror replacement",
        "ac gas refill car", "car ac service", "ac compressor repair",
        "clutch plate replacement", "brake pad change", "brake shoe replacement",
        "suspension repair", "shocker replacement", "strut mount",
        "ball joint replacement", "tie rod end", "axle repair",
        "timing belt change", "serpentine belt", "fan belt",
        "water pump replacement", "radiator repair", "thermostat replacement",
        "fuel filter change", "air filter replacement", "spark plug change",
        "car tuning", "engine overhaul", "car modification",
        "spoiler installation", "body kit", "alloy wheels",
        "car audio system", "speaker installation", "subwoofer",
        "car stereo", "android auto headunit", "reverse camera",
        "parking sensor", "dash cam installation", "gps tracker",
        "fastag recharge", "toll tax payment", "challan payment",
        "pollution certificate", "puc certificate", "fitness certificate",
        "driving license renewal", "vehicle rc renewal", "permit renewal",
        "car registration", "bike registration", "number plate",
        "car transfer ownership", "vehicle transfer", "noc certificate",
    ],
    "Pets": [
        "dog food pedigree", "cat food whiskas", "pet food monthly",
        "dog treats purchase", "cat treats", "pet snacks",
        "dog shampoo", "cat shampoo", "pet grooming products",
        "pet toys purchase", "dog toys", "cat toys",
        "pet bed purchase", "dog bed", "cat bed",
        "pet carrier", "dog crate", "cat cage",
        "litter box cat", "cat litter sand", "pet litter",
        "dog collar", "cat collar", "pet leash",
        "pet harness", "dog harness", "cat harness",
        "pet vaccination", "dog vaccine", "cat vaccine",
        "vet consultation", "pet hospital visit", "veterinary fee",
        "pet surgery", "dog surgery", "cat treatment",
        "pet medicine", "dog medicine", "cat antibiotics",
        "pet supplements", "dog vitamins", "cat supplements",
        "pet grooming service", "dog grooming", "cat grooming",
        "pet boarding", "dog kennel", "cat boarding",
        "pet sitter fee", "dog walker", "pet daycare",
        "pet training classes", "dog training", "obedience training",
        "pet accessories", "dog bowl", "cat feeder",
        "automatic feeder", "water fountain pet", "pet water dispenser",
        "aquarium setup", "fish food", "aquarium filter",
        "fish tank maintenance", "aquarium plants", "fish medicine",
        "bird food purchase", "bird cage", "bird accessories",
        "hamster cage", "rabbit hutch", "pet bedding",
        "pet insurance", "dog insurance", "cat health insurance",
        "pet id tag", "microchip pet", "gps tracker pet",
    ],
    "Baby & Kids": [
        "baby diapers pack", "newborn diapers", "huggies diapers",
        "baby wipes purchase", "baby lotion", "baby oil",
        "baby powder", "baby shampoo", "baby soap",
        "baby clothes", "newborn onesies", "baby romper",
        "kids clothes", "children wear", "school uniform",
        "baby shoes", "kids footwear", "school shoes",
        "baby formula milk", "infant formula", "baby food",
        "baby cereal", "baby snacks", "toddler food",
        "baby bottles", "feeding bottle", "sippy cup",
        "baby pacifier", "teether", "baby bibs",
        "stroller purchase", "baby pram", "baby carrier",
        "car seat baby", "baby swing", "baby bouncer",
        "crib baby", "baby cot", "baby mattress",
        "baby bedding", "baby blanket", "baby quilt",
        "baby toys", "educational toys", "soft toys",
        "kids toys", "lego set", "board games",
        "baby monitor", "night light baby", "baby thermometer",
        "baby medicine", "pediatric drops", "baby vitamins",
        "vaccination baby", "baby vaccination", "immunization",
        "pediatrician fee", "baby doctor visit", "child specialist",
        "baby furniture", "changing table", "baby dresser",
        "high chair baby", "baby walker", "play mat",
        "school bag", "kids backpack", "lunch box",
        "water bottle kids", "kids tiffin", "stationery school",
        "books children", "story books", "coloring books",
        "art supplies kids", "crayons set", "kids sketchbook",
        "kids classes", "dance class", "music class",
        "swimming class kids", "karate class", "tuition fee",
        "school fees", "college fees", "education expenses",
        "birthday party kids", "party supplies", "balloons decorations",
    ],
    "Sports & Fitness": [
        "gym membership monthly", "gym annual fee", "fitness center",
        "yoga class subscription", "pilates studio", "crossfit membership",
        "personal trainer fee", "fitness coach", "online fitness program",
        "protein powder whey", "creatine supplement", "pre workout",
        "bcaa supplement", "multivitamins fitness", "fish oil capsules",
        "gym clothes", "workout wear", "sports tshirt",
        "running shoes", "training shoes", "gym shoes",
        "sports shoes", "basketball shoes", "football boots",
        "gym equipment home", "dumbbells set", "kettlebell",
        "resistance bands", "yoga mat", "exercise mat",
        "foam roller", "jump rope", "medicine ball",
        "pull up bar", "push up handles", "ab wheel",
        "treadmill purchase", "exercise bike", "elliptical trainer",
        "rowing machine", "home gym setup", "multigym station",
        "sports gear", "cricket bat", "tennis racket",
        "badminton racket", "football", "basketball",
        "volleyball", "table tennis kit", "carrom board",
        "chess set", "sports accessories", "gym bag",
        "water bottle sports", "shaker bottle", "sports towel",
        "fitness tracker", "smart band", "heart rate monitor",
        "sports watch", "gps watch running", "cycling computer",
        "cycling gear", "bicycle helmet", "cycling shorts",
        "bicycle accessories", "bike repair", "cycle service",
        "swimming gear", "swimwear", "swimming goggles",
        "swimming cap", "pool membership", "swimming classes",
        "marathon registration", "race entry fee", "sports event ticket",
        "golf club membership", "golf equipment", "golf balls",
        "tennis court booking", "badminton court fee", "sports complex",
        "adventure sports", "trekking gear", "hiking equipment",
        "camping gear", "rock climbing", "paragliding fee",
        "scuba diving", "skydiving", "bungee jumping",
    ],
}

PREFIXES = ["", "upi ", "paid ", "payment ", "txn ", "debited ", "spent on ", "purchase "]
SUFFIXES = ["", " bill", " payment", " order", " purchase", " via upi", " online"]

# Pre-compute all prefix-suffix combinations to avoid nested loops
PREFIX_SUFFIX_COMBOS = [(p, s) for p in PREFIXES for s in SUFFIXES]


def _variants(phrase: str) -> list[str]:
    base = phrase.lower().strip()
    if not base:
        return []
    
    # Use list comprehension with set for deduplication - faster than set conversion
    seen = {base}
    variants = [base]
    
    for pre, suf in PREFIX_SUFFIX_COMBOS:
        v = f"{pre}{base}{suf}".strip()
        if len(v) >= 3 and v not in seen:
            seen.add(v)
            variants.append(v)
    
    return variants


def build() -> list[dict]:
    seen: set[str] = set()
    samples: list[dict] = []
    by_cat: dict[str, int] = {}

    # Process TRAINING_DATA_FALLBACK
    for desc, cat in TRAINING_DATA_FALLBACK:
        key = desc.lower().strip()
        if key and key not in seen:
            seen.add(key)
            samples.append({"description": key, "category": cat})
            by_cat[cat] = by_cat.get(cat, 0) + 1

    # Process EXTRA_SAMPLES with variants
    for category, phrases in EXTRA_SAMPLES.items():
        for phrase in phrases:
            for variant in _variants(phrase):
                if variant not in seen:
                    seen.add(variant)
                    samples.append({"description": variant, "category": category})
                    by_cat[category] = by_cat.get(category, 0) + 1

    return samples, by_cat


def main() -> None:
    samples, by_cat = build()
    OUT.parent.mkdir(parents=True, exist_ok=True)
    payload = {
        "version": 2,
        "description": "Curated Indian personal-finance transaction training set for Batua classifier",
        "sample_count": len(samples),
        "samples": samples,
    }
    OUT.write_text(json.dumps(payload, indent=2, ensure_ascii=False), encoding="utf-8")
    print(f"Wrote {len(samples)} samples to {OUT}")
    for cat, n in sorted(by_cat.items(), key=lambda x: -x[1]):
        print(f"  {cat}: {n}")


if __name__ == "__main__":
    main()
